/* ---------- Vocabulary data ---------- */

/* The endless-mode vocabulary (8000 French words, A1-C1, with Korean translations) lives in
   data/vocab.json rather than inline here — see data/LICENSE-DATA.md for its license
   (CC BY-SA 4.0, derived from Lexique 3.83) and methodology. It's fetched lazily and cached,
   since it's ~500KB and most visits only need it if the player picks "Traduction". */
const VOCAB_URL = "data/vocab.json";
let vocabPromise = null;

export function loadAllVocab(){
  if(!vocabPromise){
    vocabPromise = fetch(VOCAB_URL)
      .then(res => {
        if(!res.ok) throw new Error(`Impossible de charger le vocabulaire (HTTP ${res.status})`);
        return res.json();
      })
      .catch(err => { vocabPromise = null; throw err; });
  }
  return vocabPromise;
}

/* Ordered list of playable endless-mode levels. Using explicit {lvl, name} pairs (rather than
   assuming lvl is a 0-based array index) is what lets a level sit *below* A1 without renumbering
   the whole frequency-based dataset: STARTER_VOCAB below uses lvl:-1 for exactly that reason. */
export const LEVELS = [
  { lvl:-1, name:"Débutant" },
  { lvl:0, name:"A1" },
  { lvl:1, name:"A2" },
  { lvl:2, name:"B1" },
  { lvl:3, name:"B2" },
  { lvl:4, name:"C1" },
];

export function levelName(lvl){
  const found = LEVELS.find(l => l.lvl===lvl);
  return found ? found.name : "?";
}

/* Hand-picked "first words" (greetings, numbers, colors, family, everyday objects) — easier and
   more concrete than data/vocab.json's own A1 tier, which is frequency-ranked and so mixes in
   abstract verbs (falloir, devoir...) a total beginner hasn't earned yet. Small enough to stay
   inline rather than fetched. */
export const STARTER_VOCAB = [
  {fr:"bonjour", ko:"안녕하세요", lvl:-1}, {fr:"bonsoir", ko:"안녕하세요 (저녁 인사)", lvl:-1},
  {fr:"salut", ko:"안녕 (반말)", lvl:-1}, {fr:"merci", ko:"감사합니다", lvl:-1},
  {fr:"s'il vous plaît", ko:"부탁합니다", lvl:-1}, {fr:"pardon", ko:"죄송합니다, 실례합니다", lvl:-1},
  {fr:"oui", ko:"네", lvl:-1}, {fr:"non", ko:"아니요", lvl:-1},

  {fr:"maman", ko:"엄마", lvl:-1}, {fr:"papa", ko:"아빠", lvl:-1},
  {fr:"frère", ko:"형제, 오빠·형", lvl:-1}, {fr:"sœur", ko:"자매, 언니·누나", lvl:-1},
  {fr:"famille", ko:"가족", lvl:-1},

  {fr:"un", ko:"하나", lvl:-1}, {fr:"deux", ko:"둘", lvl:-1},
  {fr:"trois", ko:"셋", lvl:-1}, {fr:"quatre", ko:"넷", lvl:-1},
  {fr:"cinq", ko:"다섯", lvl:-1}, {fr:"six", ko:"여섯", lvl:-1},
  {fr:"sept", ko:"일곱", lvl:-1}, {fr:"huit", ko:"여덟", lvl:-1},
  {fr:"neuf", ko:"아홉", lvl:-1}, {fr:"dix", ko:"열", lvl:-1},

  {fr:"rouge", ko:"빨간색", lvl:-1}, {fr:"bleu", ko:"파란색", lvl:-1},
  {fr:"vert", ko:"초록색", lvl:-1}, {fr:"jaune", ko:"노란색", lvl:-1},
  {fr:"noir", ko:"검은색", lvl:-1}, {fr:"blanc", ko:"흰색", lvl:-1},
  {fr:"rose", ko:"분홍색", lvl:-1},

  {fr:"chat", ko:"고양이", lvl:-1}, {fr:"chien", ko:"개", lvl:-1},
  {fr:"oiseau", ko:"새", lvl:-1}, {fr:"poisson", ko:"물고기", lvl:-1},

  {fr:"eau", ko:"물", lvl:-1}, {fr:"pain", ko:"빵", lvl:-1},
  {fr:"pomme", ko:"사과", lvl:-1}, {fr:"lait", ko:"우유", lvl:-1},
  {fr:"sucre", ko:"설탕", lvl:-1},

  {fr:"maison", ko:"집", lvl:-1}, {fr:"porte", ko:"문", lvl:-1},
  {fr:"table", ko:"탁자, 테이블", lvl:-1}, {fr:"chaise", ko:"의자", lvl:-1},
  {fr:"livre", ko:"책", lvl:-1}, {fr:"stylo", ko:"펜", lvl:-1},

  {fr:"grand", ko:"큰", lvl:-1}, {fr:"petit", ko:"작은", lvl:-1},
  {fr:"chaud", ko:"뜨거운, 더운", lvl:-1}, {fr:"froid", ko:"차가운, 추운", lvl:-1},

  {fr:"manger", ko:"먹다", lvl:-1}, {fr:"boire", ko:"마시다", lvl:-1},
  {fr:"dormir", ko:"자다", lvl:-1}, {fr:"jouer", ko:"놀다", lvl:-1},
  {fr:"aimer", ko:"좋아하다, 사랑하다", lvl:-1},

  {fr:"aujourd'hui", ko:"오늘", lvl:-1}, {fr:"demain", ko:"내일", lvl:-1},
  {fr:"jour", ko:"낮, 날", lvl:-1}, {fr:"nuit", ko:"밤", lvl:-1},
];

/* Défis à thème — vocabulaire TCF Canada (B1→C2), classé par thème. */
export const THEME_SESSIONS = [
  { id:"verbes-analyse", title:"Verbes d'analyse & d'opinion", emoji:"🗣️", words:[
    {fr:"dénoncer", ko:"고발하다, 규탄하다, 폭로하다", lvl:3},
    {fr:"fustiger", ko:"맹비난하다, 질타하다", lvl:5},
    {fr:"regretter", ko:"후회하다, 유감스러워하다", lvl:2},
    {fr:"amèrement", ko:"씁쓸하게, 쓰라리게", lvl:4},
    {fr:"préconiser", ko:"권장하다, 권고하다", lvl:4},
    {fr:"clamer", ko:"소리 높여 주장하다, 외치다", lvl:4},
    {fr:"supplier", ko:"간청하다, 애원하다", lvl:3},
    {fr:"mépriser", ko:"경멸하다, 업신여기다", lvl:3},
    {fr:"cataloguer (qqn)", ko:"(부정적으로) 분류하다, 낙인찍다", lvl:4},
    {fr:"minimiser", ko:"축소하다, 대수롭지 않게 여기다", lvl:3},
    {fr:"se taire", ko:"침묵하다, 입을 다물다", lvl:2},
    {fr:"témoigner (de)", ko:"증언하다, 증거가 되다", lvl:3},
    {fr:"évoquer", ko:"언급하다, 떠올리다", lvl:3},
    {fr:"souligner", ko:"강조하다", lvl:3},
    {fr:"démontrer", ko:"증명하다, 입증하다", lvl:3},
    {fr:"vanter (les mérites de)", ko:"(장점을) 극찬하다, 자랑하다", lvl:4},
    {fr:"pousser qqn à (faire)", ko:"~하도록 부추기다·설득하다", lvl:2},
    {fr:"craindre / redouter", ko:"두려워하다, 우려하다", lvl:2},
    {fr:"passer pour", ko:"~으로 여겨지다, ~취급받다", lvl:3},
    {fr:"s'apercevoir de", ko:"알아차리다, 깨닫다", lvl:3},
    {fr:"s'étonner (de)", ko:"놀라다", lvl:2},
    {fr:"se moquer de", ko:"조롱하다, 비웃다", lvl:2},
    {fr:"déprimer", ko:"우울하게 하다", lvl:3},
    {fr:"relancer", ko:"재점화하다, 다시 불붙이다", lvl:3},
    {fr:"s'impatienter", ko:"조바심 내다, 초조해하다", lvl:3},
    {fr:"renoncer (à)", ko:"포기하다, 단념하다", lvl:3},
    {fr:"affronter", ko:"맞서다, 대면하다", lvl:3},
    {fr:"se battre pour", ko:"~을 위해 싸우다·투쟁하다", lvl:2},
    {fr:"bouleverser", ko:"뒤흔들다, 완전히 바꿔놓다", lvl:3},
    {fr:"plaider (pour / que)", ko:"주장하다, 옹호하다, 변호하다", lvl:4},
    {fr:"soupçonner", ko:"의심하다", lvl:3},
    {fr:"réitérer", ko:"되풀이하다, 재차 요청하다", lvl:4}
  ]},
  { id:"medias-pub", title:"Médias & Publicité", emoji:"📰", words:[
    {fr:"la publicité / la pub", ko:"광고", lvl:2},
    {fr:"un prospectus", ko:"광고 전단, 전단지", lvl:3},
    {fr:"un dépliant", ko:"접이식 전단, 리플릿", lvl:3},
    {fr:"la réclame", ko:"(옛말) 광고", lvl:4},
    {fr:"un exemplaire", ko:"부, 권 (한 부)", lvl:3},
    {fr:"une campagne", ko:"캠페인, (홍보) 운동", lvl:2},
    {fr:"une polémique", ko:"논쟁, 논란", lvl:3},
    {fr:"un débat", ko:"토론, 논쟁", lvl:2},
    {fr:"les idées reçues", ko:"고정관념, 통념", lvl:3},
    {fr:"à des fins commerciales", ko:"상업적 목적으로", lvl:4},
    {fr:"les réseaux sociaux", ko:"소셜 네트워크, SNS", lvl:2},
    {fr:"un utilisateur", ko:"사용자, 이용자", lvl:2},
    {fr:"le sujet de prédilection", ko:"가장 즐겨 찾는 주제", lvl:4},
    {fr:"un éditorial", ko:"사설", lvl:3},
    {fr:"une infographie", ko:"인포그래픽 (도표 정보)", lvl:3},
    {fr:"un quotidien", ko:"일간지", lvl:3},
    {fr:"un(e) journaliste", ko:"기자", lvl:2},
    {fr:"mettre en forme (des données)", ko:"자료를 형식화·구성하다", lvl:3},
    {fr:"les données", ko:"데이터, 자료", lvl:2},
    {fr:"les statistiques", ko:"통계", lvl:2},
    {fr:"un abonné", ko:"구독자", lvl:2},
    {fr:"s'abonner (à)", ko:"구독하다", lvl:2}
  ]},
  { id:"cinema", title:"Cinéma & Critique", emoji:"🎬", words:[
    {fr:"un réalisateur", ko:"감독", lvl:2},
    {fr:"un épisode", ko:"에피소드, (시리즈의) 편", lvl:2},
    {fr:"le genre", ko:"장르", lvl:2},
    {fr:"l'animation", ko:"애니메이션", lvl:2},
    {fr:"la comédie", ko:"코미디, 희극", lvl:2},
    {fr:"la science-fiction", ko:"공상과학, SF", lvl:2},
    {fr:"le policier (film / roman)", ko:"추리물, 형사물", lvl:2},
    {fr:"un vaisseau (spatial)", ko:"우주선", lvl:3},
    {fr:"intergalactique", ko:"은하계 간의", lvl:4},
    {fr:"foisonnant", ko:"넘쳐나는, 풍성한", lvl:4},
    {fr:"donner la migraine", ko:"골치 아프게 하다", lvl:3},
    {fr:"assommant", ko:"지루한, 따분한", lvl:4},
    {fr:"innovant", ko:"혁신적인", lvl:3},
    {fr:"passionnant", ko:"흥미진진한", lvl:2},
    {fr:"terrifiant", ko:"무서운, 소름 끼치는", lvl:3},
    {fr:"décongelé", ko:"해동된", lvl:4},
    {fr:"un acteur / une actrice", ko:"배우", lvl:2},
    {fr:"un scénario", ko:"시나리오, 각본", lvl:2},
    {fr:"le scénariste", ko:"각본가", lvl:3},
    {fr:"un tournage", ko:"촬영", lvl:3},
    {fr:"les effets spéciaux", ko:"특수효과", lvl:2},
    {fr:"un chef-d'œuvre", ko:"걸작", lvl:3},
    {fr:"la bande-annonce", ko:"예고편", lvl:2}
  ]},
  { id:"couple-psycho", title:"Couple, psychologie & violences", emoji:"🧠", words:[
    {fr:"le harcèlement", ko:"괴롭힘, 학대", lvl:3},
    {fr:"une victime", ko:"피해자", lvl:2},
    {fr:"un témoignage", ko:"증언", lvl:3},
    {fr:"par honte", ko:"부끄러움 때문에", lvl:2},
    {fr:"divorcer / le divorce", ko:"이혼하다 / 이혼", lvl:2},
    {fr:"être sous emprise", ko:"(심리적) 지배·속박 아래 있다", lvl:4},
    {fr:"l'emprise (f.)", ko:"지배, 장악, 속박", lvl:4},
    {fr:"douloureux / la douleur", ko:"고통스러운 / 고통", lvl:3},
    {fr:"la souffrance", ko:"고통", lvl:3},
    {fr:"un(e) pervers(e) narcissique", ko:"자기애성 가해자", lvl:4},
    {fr:"un manipulateur / une manipulatrice", ko:"조종하는 사람", lvl:3},
    {fr:"les dégâts", ko:"피해, 손상", lvl:3},
    {fr:"l'inverse", ko:"반대, 그 반대의 경우", lvl:3},
    {fr:"se reconstruire", ko:"재기하다, 다시 일어서다", lvl:3},
    {fr:"cacher", ko:"숨기다, 감추다", lvl:2},
    {fr:"une rupture", ko:"이별, 결별", lvl:2},
    {fr:"se réconcilier", ko:"화해하다", lvl:3},
    {fr:"la confiance", ko:"신뢰", lvl:2},
    {fr:"trahir", ko:"배신하다", lvl:3},
    {fr:"pardonner", ko:"용서하다", lvl:2},
    {fr:"un soutien psychologique", ko:"심리 지원", lvl:3},
    {fr:"s'épanouir", ko:"성장하다, 만개하다", lvl:3}
  ]},
  { id:"drogue-sante", title:"Drogue & Santé publique", emoji:"💊", words:[
    {fr:"la toxicomanie", ko:"약물 중독, 마약 중독", lvl:4},
    {fr:"un usager (de drogue)", ko:"(마약) 사용자", lvl:3},
    {fr:"la consommation", ko:"소비, 복용", lvl:2},
    {fr:"à moindres risques", ko:"위험을 줄인, 저위험의", lvl:3},
    {fr:"réduire / diminuer", ko:"줄이다 / 감소시키다", lvl:2},
    {fr:"les risques sanitaires", ko:"보건상의 위험", lvl:3},
    {fr:"sanitaire", ko:"위생의, 보건의", lvl:3},
    {fr:"les nuisances", ko:"폐해, 피해", lvl:4},
    {fr:"l'espace public", ko:"공공 공간", lvl:3},
    {fr:"encadrer", ko:"관리·감독하다, 지도하다", lvl:3},
    {fr:"être implanté (au…)", ko:"~에 설치되다, 자리 잡다", lvl:3},
    {fr:"un professionnel de la santé", ko:"의료 종사자", lvl:2},
    {fr:"un accueil", ko:"응대, 수용, 맞이함", lvl:2},
    {fr:"une dépendance", ko:"의존, 중독", lvl:3},
    {fr:"le sevrage", ko:"금단, 해독", lvl:4},
    {fr:"une overdose", ko:"과다복용", lvl:3},
    {fr:"prévenir (les risques)", ko:"예방하다", lvl:2},
    {fr:"un centre de désintoxication", ko:"재활 센터", lvl:4},
    {fr:"la dépénalisation", ko:"비범죄화", lvl:4},
    {fr:"un stupéfiant", ko:"마약, 마취제", lvl:3},
    {fr:"soigner", ko:"치료하다", lvl:2}
  ]},
  { id:"voyage-admin", title:"Voyage, immigration & administration", emoji:"🛂", words:[
    {fr:"la garde partagée / légale", ko:"공동 양육권 / 법적 양육권", lvl:4},
    {fr:"les droits de visite", ko:"면접교섭권, 방문권", lvl:4},
    {fr:"les parents séparés / divorcés", ko:"별거·이혼 부모", lvl:3},
    {fr:"la progéniture", ko:"자손, 자녀", lvl:4},
    {fr:"les papiers d'identité", ko:"신분증(류)", lvl:2},
    {fr:"une lettre d'autorisation", ko:"허가서, 동의서", lvl:3},
    {fr:"la frontière", ko:"국경", lvl:2},
    {fr:"un enlèvement (d'enfant)", ko:"(아동) 유괴, 납치", lvl:3},
    {fr:"un acte criminel", ko:"범죄 행위", lvl:3},
    {fr:"les douanes", ko:"세관 / 세관원", lvl:3},
    {fr:"un porte-parole", ko:"대변인", lvl:3},
    {fr:"se munir de", ko:"~을 지참하다, 갖추다", lvl:4},
    {fr:"un ressortissant", ko:"국민, 국적자", lvl:4},
    {fr:"un pays tiers", ko:"제3국 (역외 국가)", lvl:4},
    {fr:"soumis à visa", ko:"비자가 필요한", lvl:4},
    {fr:"un court séjour", ko:"단기 체류", lvl:3},
    {fr:"la zone / l'espace Schengen", ko:"솅겐 지역·구역", lvl:3},
    {fr:"un visa / un passeport", ko:"비자 / 여권", lvl:2},
    {fr:"un État membre", ko:"회원국", lvl:3},
    {fr:"valable / en cours de validité", ko:"유효한 / 유효기간 내의", lvl:3},
    {fr:"le cas échéant", ko:"경우에 따라, 필요한 경우", lvl:4},
    {fr:"les moyens de subsistance", ko:"생계 수단", lvl:4},
    {fr:"faire l'objet de", ko:"~의 대상이 되다", lvl:4},
    {fr:"un signalement", ko:"신고, 통보", lvl:4},
    {fr:"aux fins de non-admission", ko:"입국 거부를 위한", lvl:5},
    {fr:"le titulaire", ko:"소지자, 명의인", lvl:3},
    {fr:"la liberté de circulation", ko:"이동의 자유", lvl:3},
    {fr:"le territoire", ko:"영토, 지역", lvl:3},
    {fr:"l'apposition (d'un cachet)", ko:"(도장) 날인, 찍음", lvl:5},
    {fr:"un cachet", ko:"도장, 스탬프", lvl:3},
    {fr:"le délai (de séjour)", ko:"기한, (체류) 기간", lvl:3},
    {fr:"un certificat d'hébergement", ko:"숙박 증명서", lvl:4},
    {fr:"attester / prouver / justifier", ko:"증명·입증하다", lvl:3},
    {fr:"un litige", ko:"분쟁, 소송", lvl:4},
    {fr:"les autorités judiciaires", ko:"사법 당국", lvl:4},
    {fr:"différer (un voyage)", ko:"(여행을) 미루다, 연기하다", lvl:4}
  ]},
  { id:"societe-politique", title:"Société, histoire & politique", emoji:"🏛️", words:[
    {fr:"la contraception", ko:"피임", lvl:3},
    {fr:"un pionnier", ko:"선구자, 개척자", lvl:3},
    {fr:"une infection pulmonaire", ko:"폐 감염, 폐렴", lvl:3},
    {fr:"la Résistance", ko:"레지스탕스, 저항운동", lvl:3},
    {fr:"un député / un sénateur", ko:"하원의원 / 상원의원", lvl:3},
    {fr:"le Sénat / le Parlement", ko:"상원 / 의회", lvl:3},
    {fr:"conservateur / conservatrice", ko:"보수적인, 보수주의의", lvl:3},
    {fr:"adopter / voter (une loi)", ko:"법을 채택·가결하다", lvl:3},
    {fr:"un élu", ko:"선출직 공직자", lvl:3},
    {fr:"un malfaiteur (public)", ko:"악인, 범죄자", lvl:4},
    {fr:"une invective", ko:"욕설, 독설, 비난", lvl:4},
    {fr:"la régulation des naissances", ko:"산아 제한", lvl:4},
    {fr:"sur ordonnance médicale", ko:"의사 처방으로", lvl:3},
    {fr:"une autorisation parentale", ko:"부모 동의", lvl:3},
    {fr:"un(e) mineur(e)", ko:"미성년자", lvl:3},
    {fr:"affable", ko:"상냥한, 붙임성 있는", lvl:4},
    {fr:"un agent de liaison", ko:"연락 요원", lvl:4},
    {fr:"un homme de conviction", ko:"신념의 사람", lvl:3},
    {fr:"ses pairs", ko:"동료들, 또래", lvl:4},
    {fr:"la législation", ko:"법제, 입법, 법령", lvl:3},
    {fr:"l'exclusion (du gouvernement)", ko:"배제, 축출", lvl:3},
    {fr:"la retraite / une pension", ko:"은퇴·연금", lvl:2},
    {fr:"un fonctionnaire", ko:"공무원", lvl:2},
    {fr:"une réforme", ko:"개혁", lvl:3},
    {fr:"un sondage", ko:"여론조사", lvl:3},
    {fr:"favorable à", ko:"~에 찬성하는, 우호적인", lvl:3},
    {fr:"le salaire / un salarié", ko:"급여 / 임금 노동자", lvl:2},
    {fr:"le secteur public / privé", ko:"공공 / 민간 부문", lvl:3},
    {fr:"une mesure", ko:"조치, 대책", lvl:3},
    {fr:"un sympathisant (de gauche / de droite)", ko:"좌파/우파 지지자", lvl:4},
    {fr:"un rapport", ko:"보고서", lvl:2},
    {fr:"une piste", ko:"실마리, 방안", lvl:3},
    {fr:"s'appuyer sur", ko:"~에 근거하다, 의지하다", lvl:3},
    {fr:"remettre (un rapport)", ko:"보고서를 제출하다", lvl:3},
    {fr:"une harmonisation", ko:"조율, 일원화, 표준화", lvl:4},
    {fr:"une indemnisation", ko:"보상", lvl:4},
    {fr:"une tranche (d'années)", ko:"구간, 단계", lvl:3},
    {fr:"une revalorisation", ko:"인상, 상향 조정", lvl:4},
    {fr:"un écart", ko:"격차, 차이", lvl:3},
    {fr:"une prime", ko:"수당, 상여금, 보너스", lvl:3}
  ]},
  { id:"techno-vie-privee", title:"Technologie & vie privée", emoji:"📱", words:[
    {fr:"la jalousie", ko:"질투", lvl:2},
    {fr:"un texto", ko:"문자 메시지", lvl:2},
    {fr:"les échanges épistolaires", ko:"서신 교환", lvl:4},
    {fr:"se remémorer", ko:"회상하다, 다시 떠올리다", lvl:4},
    {fr:"le portable", ko:"휴대폰", lvl:2},
    {fr:"un(e) partenaire", ko:"파트너, 상대", lvl:2},
    {fr:"l'infidélité / fidèle", ko:"부정·불륜 / 충실한", lvl:3},
    {fr:"fouiller (dans)", ko:"뒤지다, 샅샅이 찾다", lvl:3},
    {fr:"une preuve", ko:"증거", lvl:2},
    {fr:"le mensonge", ko:"거짓말", lvl:2},
    {fr:"la curiosité", ko:"호기심", lvl:2},
    {fr:"inné", ko:"타고난, 선천적인", lvl:4},
    {fr:"le respect de la vie privée", ko:"사생활 존중", lvl:3},
    {fr:"à la portée de", ko:"손이 닿는 곳에, 접근 가능한", lvl:4},
    {fr:"jurer fidélité", ko:"정절을 맹세하다", lvl:4},
    {fr:"un comportement", ko:"행동, 태도, 처신", lvl:3},
    {fr:"pirater", ko:"해킹하다", lvl:3},
    {fr:"les données personnelles", ko:"개인정보", lvl:2},
    {fr:"surveiller", ko:"감시하다", lvl:3},
    {fr:"un réseau social", ko:"소셜 네트워크", lvl:2},
    {fr:"anonyme", ko:"익명의", lvl:3},
    {fr:"une application", ko:"애플리케이션, 앱", lvl:2}
  ]},
  { id:"tourisme", title:"Tourisme", emoji:"🗺️", words:[
    {fr:"jadis", ko:"옛날에, 예전에", lvl:4},
    {fr:"un point de vue", ko:"전망 / 관점", lvl:2},
    {fr:"une auberge", ko:"여관, 여인숙", lvl:3},
    {fr:"un vicaire", ko:"보좌 신부", lvl:4},
    {fr:"humble", ko:"소박한, 겸손한", lvl:3},
    {fr:"la cheffe / le chef", ko:"셰프, 주방장", lvl:2},
    {fr:"accueillir", ko:"맞이하다, 환대하다", lvl:2},
    {fr:"ripailler", ko:"진탕 먹고 마시다, 잔치를 벌이다", lvl:5},
    {fr:"un fjord", ko:"피오르 (협만)", lvl:4},
    {fr:"un fil (électrique) / un poteau", ko:"전선 / 기둥, 전봇대", lvl:2},
    {fr:"balafrer (le décor)", ko:"풍경을 흉하게 망치다", lvl:5},
    {fr:"une griffure", ko:"긁힌 자국", lvl:4},
    {fr:"bannir", ko:"추방하다, 금지하다, 없애다", lvl:4},
    {fr:"un fléau", ko:"재앙, 골칫거리", lvl:4},
    {fr:"l'isolement", ko:"고립, 외딴곳(임)", lvl:3},
    {fr:"une installation électrique", ko:"전기 시설", lvl:3},
    {fr:"le parvis (d'une cathédrale)", ko:"(성당 앞) 광장", lvl:4},
    {fr:"la file (d'attente)", ko:"줄, 대기열", lvl:2},
    {fr:"un guichet", ko:"창구, 매표소", lvl:3},
    {fr:"patienter", ko:"기다리다, 참고 기다리다", lvl:3},
    {fr:"gravir (un escalier)", ko:"계단을 힘겹게 오르다", lvl:4},
    {fr:"un escalier en colimaçon", ko:"나선 계단", lvl:4},
    {fr:"s'attarder", ko:"지체하다, 오래 머무르다", lvl:4},
    {fr:"le panorama", ko:"파노라마, 전경", lvl:3},
    {fr:"un revendeur à la sauvette", ko:"노점상·무허가 행상", lvl:4},
    {fr:"ça vaut le coup", ko:"그럴 만한 가치가 있다", lvl:3},
    {fr:"l'affluence", ko:"붐빔, 혼잡, 인파", lvl:4},
    {fr:"le tourisme de masse", ko:"대중 관광", lvl:3},
    {fr:"le mauvais accueil", ko:"나쁜 응대·대접", lvl:2}
  ]},
  { id:"environnement-theme", title:"Environnement", emoji:"🌍", words:[
    {fr:"la sécheresse", ko:"가뭄", lvl:3},
    {fr:"la météorologie", ko:"기상(학), 날씨", lvl:3},
    {fr:"défavorable", ko:"불리한", lvl:3},
    {fr:"découler de", ko:"~에서 비롯되다·기인하다", lvl:4},
    {fr:"archaïque", ko:"낡은, 시대에 뒤진", lvl:4},
    {fr:"une synthèse", ko:"종합, 요약 보고서", lvl:3},
    {fr:"une inflexion", ko:"방향 전환, 변화", lvl:4},
    {fr:"la gestion (des ressources)", ko:"자원 관리, 운영", lvl:2},
    {fr:"les ressources", ko:"자원", lvl:2},
    {fr:"rare", ko:"드문, 희소한", lvl:2},
    {fr:"une restriction (d'eau)", ko:"(물) 제한", lvl:3},
    {fr:"de dernière minute", ko:"막판의, 임박한", lvl:3},
    {fr:"en finir avec", ko:"~을 끝내다, 종지부를 찍다", lvl:3},
    {fr:"la surconsommation", ko:"과소비", lvl:4},
    {fr:"une prévision", ko:"예측, 전망", lvl:3},
    {fr:"la défaillance", ko:"결함, 미흡함, 실패", lvl:4},
    {fr:"les autorités", ko:"당국", lvl:3},
    {fr:"la malchance", ko:"불운", lvl:3},
    {fr:"le réchauffement climatique", ko:"지구 온난화", lvl:2},
    {fr:"la pollution", ko:"오염", lvl:2},
    {fr:"recycler", ko:"재활용하다", lvl:2},
    {fr:"une énergie renouvelable", ko:"재생 에너지", lvl:3}
  ]},
  { id:"correspondance-admin", title:"Correspondance administrative", emoji:"✉️", words:[
    {fr:"accuser réception de", ko:"수령을 확인·통지하다", lvl:4},
    {fr:"un courrier", ko:"우편물, 편지, 서신", lvl:3},
    {fr:"apporter une attention particulière (à)", ko:"특별히 유의하다", lvl:3},
    {fr:"concernant", ko:"~에 관하여", lvl:3},
    {fr:"les conditions d'accueil", ko:"응대·접수 조건", lvl:3},
    {fr:"alerter (qqn sur)", ko:"경고하다, 알리다", lvl:3},
    {fr:"confirmer", ko:"확인하다, 확정하다", lvl:2},
    {fr:"la délivrance (de documents)", ko:"(서류의) 발급", lvl:4},
    {fr:"selon les normes établies", ko:"정해진 기준에 따라", lvl:3},
    {fr:"un ministère", ko:"(정부) 부처", lvl:3},
    {fr:"assurer (que)", ko:"보장하다, 확언하다", lvl:2},
    {fr:"le destinataire", ko:"수신인", lvl:3},
    {fr:"une demande", ko:"요청·신청 / 신청 처리", lvl:2},
    {fr:"je vous prie de croire… en mes meilleurs sentiments", ko:"(격식 편지의 맺음말) ~올림", lvl:4},
    {fr:"se comporter", ko:"처신·행동하다", lvl:3},
    {fr:"une pièce jointe", ko:"첨부 파일", lvl:2},
    {fr:"un formulaire", ko:"서식, 양식", lvl:2},
    {fr:"remplir (un formulaire)", ko:"서식을 작성하다", lvl:2},
    {fr:"un accusé de réception", ko:"수령 확인(서)", lvl:3},
    {fr:"un délai de réponse", ko:"답변 기한", lvl:3},
    {fr:"transmettre (un dossier)", ko:"서류를 전달하다", lvl:3}
  ]},
  { id:"argot-slang", title:"Argot & langage ultra familier", emoji:"🔥", words:[
    {fr:"un mec", ko:"녀석, 남자", lvl:2},
    {fr:"une meuf", ko:"여자, 여친 (verlan de 'femme')", lvl:3},
    {fr:"un pote", ko:"친구", lvl:2},
    {fr:"bouffer", ko:"처먹다, 먹다", lvl:2},
    {fr:"kiffer", ko:"완전 좋아하다", lvl:2},
    {fr:"chelou", ko:"이상한 (verlan de 'louche')", lvl:3},
    {fr:"relou", ko:"짜증나는, 귀찮은 (verlan de 'lourd')", lvl:3},
    {fr:"la flemme", ko:"귀찮음, 하기 싫음", lvl:3},
    {fr:"grave", ko:"완전, 진짜 (강조)", lvl:2},
    {fr:"ouf", ko:"미친, 대박 (verlan de 'fou')", lvl:3},
    {fr:"taffer / le taf", ko:"일하다 / 일", lvl:3},
    {fr:"la thune", ko:"돈", lvl:3},
    {fr:"une bagnole", ko:"차", lvl:2},
    {fr:"les fringues", ko:"옷", lvl:2},
    {fr:"une clope", ko:"담배", lvl:3},
    {fr:"piger", ko:"이해하다", lvl:3},
    {fr:"se marrer", ko:"웃다, 즐거워하다", lvl:3},
    {fr:"gueuler", ko:"소리 지르다", lvl:3},
    {fr:"avoir la dalle", ko:"배고프다", lvl:3},
    {fr:"être crevé(e)", ko:"완전 지치다", lvl:2},
    {fr:"un truc / un machin", ko:"물건, 그거", lvl:2},
    {fr:"nickel", ko:"완벽해, 딱 좋아", lvl:2},
    {fr:"ça déchire", ko:"완전 최고다", lvl:3},
    {fr:"dégager", ko:"꺼지다, 나가다", lvl:3},
    {fr:"wesh", ko:"야 (캐주얼한 인사)", lvl:3},
    {fr:"une galère", ko:"개고생, 힘든 상황", lvl:3}
  ]}
];
